### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by tesch1**
Hi,

This cleans up a bunch of warnings, along with adding a build file for cmake.
Also removed include of nfft3utils.h since newer versions of nfft3 dont have it.
Tested on Centos7 and macos 10.12.

Hope it's useful for someone.  Let me know if there's anything you'd like cleaned up to make it mergeable!

Cheers

### CODE REVIEW

**Comment by jcwright77** [comment]
cmake file gone again? Are there build instructions anywhere?

**Comment by tesch1** [comment]
see #4

**Comment by jcwright77** [comment]
that appears to be a pull request that has not been accepted. The repo (vosegaard/simpson) has only a master branch and no tags or branches.
Can you point me to an actual branch that can be checked out? I guess you are suggesting I cut and paste the contents of your pull request? 

-john

**Comment by tesch1** [comment]
the repo tesch1/simpson, however, has the branch build-cmake from which the pull is requested.  you can check that out - there's a link directly to it in the #4 PR page.

**Comment by jcwright77** [comment]
Thanks. There is a link to your github page but not to tesch1/simpson directly. And from there I found the simpson repo.

-john

**Comment by tesch1** [comment]
ah, maybe it only shows me the link because it's my branch.

**Pull request closed without merging**
